// WARNING: This file was autogenerated; DO NOT EDIT.

#[doc(hidden)]
pub mod apu_test {
    use harness;
    pub fn testcase_1_len_ctr< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/1-len_ctr.nes" );

        harness::standard_testcase::< T >( ROM, "5111d60a4db76c22731b4017d76a2f31", 18 );
    }
    pub fn testcase_2_len_table< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/2-len_table.nes" );

        harness::standard_testcase::< T >( ROM, "b0ffa7caf7ab376c9929186e2f3173e9", 13 );
    }
    pub fn testcase_3_irq_flag< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/3-irq_flag.nes" );

        harness::standard_testcase::< T >( ROM, "5c344bde6be07e250485c0a69fea301e", 18 );
    }
    pub fn testcase_4_jitter< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/4-jitter.nes" );

        harness::standard_testcase::< T >( ROM, "1916d2178cc8bc3ed66df23ec137c2d8", 18 );
    }
    pub fn testcase_5_len_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/5-len_timing.nes" );

        harness::standard_testcase::< T >( ROM, "107d4aefe84e9e854fa9b871175c3773", 111 );
    }
    pub fn testcase_6_irq_flag_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/6-irq_flag_timing.nes" );

        harness::standard_testcase::< T >( ROM, "c5843d4f656d6b126e49b4754e91900b", 19 );
    }
    pub fn testcase_7_dmc_basics< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/7-dmc_basics.nes" );

        harness::standard_testcase::< T >( ROM, "f1b668840f36ba90cd137fe5eb7dfde0", 22 );
    }
    pub fn testcase_8_dmc_rates< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/apu_test/8-dmc_rates.nes" );

        harness::standard_testcase::< T >( ROM, "f9a236839337d7642fe437caf456c480", 26 );
    }
}
pub mod blargg_apu_2005_07_30 {
    use harness;
    pub fn testcase_01_len_ctr< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_apu_2005.07.30/01.len_ctr.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 25 );
    }
    pub fn testcase_02_len_table< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_apu_2005.07.30/02.len_table.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 12 );
    }
    pub fn testcase_03_irq_flag< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_apu_2005.07.30/03.irq_flag.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 17 );
    }
    pub fn testcase_04_clock_jitter< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_apu_2005.07.30/04.clock_jitter.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 16 );
    }
    pub fn testcase_05_len_timing_mode0< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_apu_2005.07.30/05.len_timing_mode0.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 21 );
    }
    pub fn testcase_06_len_timing_mode1< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_apu_2005.07.30/06.len_timing_mode1.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 24 );
    }
    pub fn testcase_07_irq_flag_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_apu_2005.07.30/07.irq_flag_timing.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 18 );
    }
}
pub mod blargg_ppu_tests_2005_09_15b {
    use harness;
    pub fn testcase_palette_ram< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_ppu_tests_2005.09.15b/palette_ram.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 20 );
    }
    pub fn testcase_vbl_clear_time< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_ppu_tests_2005.09.15b/vbl_clear_time.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 25 );
    }
    pub fn testcase_vram_access< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/blargg_ppu_tests_2005.09.15b/vram_access.nes" );

        harness::standard_testcase::< T >( ROM, "0941a56e4c62c6026264952a9bfaea35", 20 );
    }
}
pub mod branch_timing_tests {
    use harness;
    pub fn testcase_1_branch_basics< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/branch_timing_tests/1.Branch_Basics.nes" );

        harness::standard_testcase::< T >( ROM, "d0ba5841977f79774975eded5685d18c", 13 );
    }
    pub fn testcase_2_backward_branch< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/branch_timing_tests/2.Backward_Branch.nes" );

        harness::standard_testcase::< T >( ROM, "f8fedc8a1651b25f4f08ff40e6ece447", 16 );
    }
    pub fn testcase_3_forward_branch< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/branch_timing_tests/3.Forward_Branch.nes" );

        harness::standard_testcase::< T >( ROM, "9e4f736ac2ce791126ce2e6c3174b930", 15 );
    }
}
pub mod dmc_dma_during_read4 {
    use harness;
    pub fn testcase_read_write_2007< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/dmc_dma_during_read4/read_write_2007.nes" );

        harness::standard_testcase::< T >( ROM, "88608a8ed0cf18ef708519de1143db9e", 18 );
    }
}
pub mod instr_misc {
    use harness;
    pub fn testcase_01_abs_x_wrap< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/instr_misc/01-abs_x_wrap.nes" );

        harness::standard_testcase::< T >( ROM, "a9ca82047bb04a64afd3949699615afc", 12 );
    }
    pub fn testcase_02_branch_wrap< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/instr_misc/02-branch_wrap.nes" );

        harness::standard_testcase::< T >( ROM, "b5d3a5b428304a71c81436edc6f511e7", 12 );
    }
    pub fn testcase_03_dummy_reads< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/instr_misc/03-dummy_reads.nes" );

        harness::standard_testcase::< T >( ROM, "704d3a7d459675125709aa4eaab43b69", 56 );
    }
}
pub mod oam_read {
    use harness;
    pub fn testcase_oam_read< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/oam_read/oam_read.nes" );

        harness::standard_testcase::< T >( ROM, "7909f77fe22ff669e107f5334134ad0b", 28 );
    }
}
pub mod sprite_hit_tests_2005_10_05 {
    use harness;
    pub fn testcase_01_basics< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/01.basics.nes" );

        harness::standard_testcase::< T >( ROM, "388ab951797a627282c6a43b8aca0692", 33 );
    }
    pub fn testcase_02_alignment< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/02.alignment.nes" );

        harness::standard_testcase::< T >( ROM, "efe0e20c14ae43c7b3c511d2ab08950c", 31 );
    }
    pub fn testcase_03_corners< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/03.corners.nes" );

        harness::standard_testcase::< T >( ROM, "7ff7c9bc044afd3855c82da016504423", 21 );
    }
    pub fn testcase_04_flip< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/04.flip.nes" );

        harness::standard_testcase::< T >( ROM, "c1bc9a362d15c196efd55704c33f7fc9", 19 );
    }
    pub fn testcase_05_left_clip< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/05.left_clip.nes" );

        harness::standard_testcase::< T >( ROM, "e8ab4d728f702d0ad1c2c00e8208dc38", 29 );
    }
    pub fn testcase_06_right_edge< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/06.right_edge.nes" );

        harness::standard_testcase::< T >( ROM, "cd8c9e59befaa11d5a261492fe0d2125", 23 );
    }
    pub fn testcase_07_screen_bottom< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/07.screen_bottom.nes" );

        harness::standard_testcase::< T >( ROM, "6e946157b0a4575ad28dd77d6a0998bd", 24 );
    }
    pub fn testcase_08_double_height< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/08.double_height.nes" );

        harness::standard_testcase::< T >( ROM, "b8cb45dfdf1c7fed572aa910d03c48db", 20 );
    }
    pub fn testcase_09_timing_basics< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/09.timing_basics.nes" );

        harness::standard_testcase::< T >( ROM, "ab27927fd0393001a12acd99d13020cc", 63 );
    }
    pub fn testcase_10_timing_order< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/10.timing_order.nes" );

        harness::standard_testcase::< T >( ROM, "1fa4915b3c7ef833bdc5b7a1c7d77055", 59 );
    }
    pub fn testcase_11_edge_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_tests_2005.10.05/11.edge_timing.nes" );

        harness::standard_testcase::< T >( ROM, "1cc6471b69a9b850851ca2c127261dfc", 54 );
    }
}
pub mod sprite_hit_timing {
    use harness;
    pub fn testcase_sprite_hit_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/sprite_hit_timing/sprite_hit_timing.nes" );

        harness::standard_testcase::< T >( ROM, "ffe8f3026500a839ba7d528ac52d21b0", 92 );
    }
}
pub mod vbl_nmi_timing {
    use harness;
    pub fn testcase_1_frame_basics< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/vbl_nmi_timing/1.frame_basics.nes" );

        harness::standard_testcase::< T >( ROM, "b6c0c4c438349b0f37df7df15679f103", 177 );
    }
    pub fn testcase_2_vbl_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/vbl_nmi_timing/2.vbl_timing.nes" );

        harness::standard_testcase::< T >( ROM, "4390eee80911ddcef3c5ba633ba96780", 152 );
    }
    pub fn testcase_3_even_odd_frames< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/vbl_nmi_timing/3.even_odd_frames.nes" );

        harness::standard_testcase::< T >( ROM, "cfa81bdc8309c4ff06f75fd1cc87d3e0", 97 );
    }
    pub fn testcase_4_vbl_clear_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/vbl_nmi_timing/4.vbl_clear_timing.nes" );

        harness::standard_testcase::< T >( ROM, "c0e78f389727610faf0bf868fc0edac9", 115 );
    }
    pub fn testcase_5_nmi_suppression< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/vbl_nmi_timing/5.nmi_suppression.nes" );

        harness::standard_testcase::< T >( ROM, "2ff7a07783430542eff3169942a4e617", 164 );
    }
    pub fn testcase_6_nmi_disable< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/vbl_nmi_timing/6.nmi_disable.nes" );

        harness::standard_testcase::< T >( ROM, "45e1c4cf3394f6ba15083b5ab25e72ff", 107 );
    }
    pub fn testcase_7_nmi_timing< T: harness::EmulatorInterface >() {
        static ROM: &'static [u8] = include_bytes!( "../roms/vbl_nmi_timing/7.nmi_timing.nes" );

        harness::standard_testcase::< T >( ROM, "bce0c0c99010f60d94a9c80f3f7532b3", 107 );
    }
}

#[macro_export]
macro_rules! nes_testsuite {
    ($interface:ident) => (
        mod apu_test {
            #[test]
            fn testcase_1_len_ctr() {
                use super::$interface;
                $crate::tests::apu_test::testcase_1_len_ctr::< $interface >();
            }
            #[test]
            fn testcase_2_len_table() {
                use super::$interface;
                $crate::tests::apu_test::testcase_2_len_table::< $interface >();
            }
            #[test]
            fn testcase_3_irq_flag() {
                use super::$interface;
                $crate::tests::apu_test::testcase_3_irq_flag::< $interface >();
            }
            #[test]
            fn testcase_4_jitter() {
                use super::$interface;
                $crate::tests::apu_test::testcase_4_jitter::< $interface >();
            }
            #[test]
            fn testcase_5_len_timing() {
                use super::$interface;
                $crate::tests::apu_test::testcase_5_len_timing::< $interface >();
            }
            #[test]
            fn testcase_6_irq_flag_timing() {
                use super::$interface;
                $crate::tests::apu_test::testcase_6_irq_flag_timing::< $interface >();
            }
            #[test]
            fn testcase_7_dmc_basics() {
                use super::$interface;
                $crate::tests::apu_test::testcase_7_dmc_basics::< $interface >();
            }
            #[test]
            fn testcase_8_dmc_rates() {
                use super::$interface;
                $crate::tests::apu_test::testcase_8_dmc_rates::< $interface >();
            }
        }
        mod blargg_apu_2005_07_30 {
            #[test]
            fn testcase_01_len_ctr() {
                use super::$interface;
                $crate::tests::blargg_apu_2005_07_30::testcase_01_len_ctr::< $interface >();
            }
            #[test]
            fn testcase_02_len_table() {
                use super::$interface;
                $crate::tests::blargg_apu_2005_07_30::testcase_02_len_table::< $interface >();
            }
            #[test]
            fn testcase_03_irq_flag() {
                use super::$interface;
                $crate::tests::blargg_apu_2005_07_30::testcase_03_irq_flag::< $interface >();
            }
            #[test]
            fn testcase_04_clock_jitter() {
                use super::$interface;
                $crate::tests::blargg_apu_2005_07_30::testcase_04_clock_jitter::< $interface >();
            }
            #[test]
            fn testcase_05_len_timing_mode0() {
                use super::$interface;
                $crate::tests::blargg_apu_2005_07_30::testcase_05_len_timing_mode0::< $interface >();
            }
            #[test]
            fn testcase_06_len_timing_mode1() {
                use super::$interface;
                $crate::tests::blargg_apu_2005_07_30::testcase_06_len_timing_mode1::< $interface >();
            }
            #[test]
            fn testcase_07_irq_flag_timing() {
                use super::$interface;
                $crate::tests::blargg_apu_2005_07_30::testcase_07_irq_flag_timing::< $interface >();
            }
        }
        mod blargg_ppu_tests_2005_09_15b {
            #[test]
            fn testcase_palette_ram() {
                use super::$interface;
                $crate::tests::blargg_ppu_tests_2005_09_15b::testcase_palette_ram::< $interface >();
            }
            #[test]
            fn testcase_vbl_clear_time() {
                use super::$interface;
                $crate::tests::blargg_ppu_tests_2005_09_15b::testcase_vbl_clear_time::< $interface >();
            }
            #[test]
            fn testcase_vram_access() {
                use super::$interface;
                $crate::tests::blargg_ppu_tests_2005_09_15b::testcase_vram_access::< $interface >();
            }
        }
        mod branch_timing_tests {
            #[test]
            fn testcase_1_branch_basics() {
                use super::$interface;
                $crate::tests::branch_timing_tests::testcase_1_branch_basics::< $interface >();
            }
            #[test]
            fn testcase_2_backward_branch() {
                use super::$interface;
                $crate::tests::branch_timing_tests::testcase_2_backward_branch::< $interface >();
            }
            #[test]
            fn testcase_3_forward_branch() {
                use super::$interface;
                $crate::tests::branch_timing_tests::testcase_3_forward_branch::< $interface >();
            }
        }
        mod dmc_dma_during_read4 {
            #[test]
            fn testcase_read_write_2007() {
                use super::$interface;
                $crate::tests::dmc_dma_during_read4::testcase_read_write_2007::< $interface >();
            }
        }
        mod instr_misc {
            #[test]
            fn testcase_01_abs_x_wrap() {
                use super::$interface;
                $crate::tests::instr_misc::testcase_01_abs_x_wrap::< $interface >();
            }
            #[test]
            fn testcase_02_branch_wrap() {
                use super::$interface;
                $crate::tests::instr_misc::testcase_02_branch_wrap::< $interface >();
            }
            #[test]
            fn testcase_03_dummy_reads() {
                use super::$interface;
                $crate::tests::instr_misc::testcase_03_dummy_reads::< $interface >();
            }
        }
        mod oam_read {
            #[test]
            fn testcase_oam_read() {
                use super::$interface;
                $crate::tests::oam_read::testcase_oam_read::< $interface >();
            }
        }
        mod sprite_hit_tests_2005_10_05 {
            #[test]
            fn testcase_01_basics() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_01_basics::< $interface >();
            }
            #[test]
            fn testcase_02_alignment() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_02_alignment::< $interface >();
            }
            #[test]
            fn testcase_03_corners() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_03_corners::< $interface >();
            }
            #[test]
            fn testcase_04_flip() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_04_flip::< $interface >();
            }
            #[test]
            fn testcase_05_left_clip() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_05_left_clip::< $interface >();
            }
            #[test]
            fn testcase_06_right_edge() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_06_right_edge::< $interface >();
            }
            #[test]
            fn testcase_07_screen_bottom() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_07_screen_bottom::< $interface >();
            }
            #[test]
            fn testcase_08_double_height() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_08_double_height::< $interface >();
            }
            #[test]
            fn testcase_09_timing_basics() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_09_timing_basics::< $interface >();
            }
            #[test]
            fn testcase_10_timing_order() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_10_timing_order::< $interface >();
            }
            #[test]
            fn testcase_11_edge_timing() {
                use super::$interface;
                $crate::tests::sprite_hit_tests_2005_10_05::testcase_11_edge_timing::< $interface >();
            }
        }
        mod sprite_hit_timing {
            #[test]
            fn testcase_sprite_hit_timing() {
                use super::$interface;
                $crate::tests::sprite_hit_timing::testcase_sprite_hit_timing::< $interface >();
            }
        }
        mod vbl_nmi_timing {
            #[test]
            fn testcase_1_frame_basics() {
                use super::$interface;
                $crate::tests::vbl_nmi_timing::testcase_1_frame_basics::< $interface >();
            }
            #[test]
            fn testcase_2_vbl_timing() {
                use super::$interface;
                $crate::tests::vbl_nmi_timing::testcase_2_vbl_timing::< $interface >();
            }
            #[test]
            fn testcase_3_even_odd_frames() {
                use super::$interface;
                $crate::tests::vbl_nmi_timing::testcase_3_even_odd_frames::< $interface >();
            }
            #[test]
            fn testcase_4_vbl_clear_timing() {
                use super::$interface;
                $crate::tests::vbl_nmi_timing::testcase_4_vbl_clear_timing::< $interface >();
            }
            #[test]
            fn testcase_5_nmi_suppression() {
                use super::$interface;
                $crate::tests::vbl_nmi_timing::testcase_5_nmi_suppression::< $interface >();
            }
            #[test]
            fn testcase_6_nmi_disable() {
                use super::$interface;
                $crate::tests::vbl_nmi_timing::testcase_6_nmi_disable::< $interface >();
            }
            #[test]
            fn testcase_7_nmi_timing() {
                use super::$interface;
                $crate::tests::vbl_nmi_timing::testcase_7_nmi_timing::< $interface >();
            }
        }
    )
}
