// This file was AUTOGENERATED; do not edit!

mod test_current_address_during_background_rendering;
mod test_current_address_during_sprite_rendering;
mod test_current_address_during_sprite_rendering_without_sprites;
mod test_current_address_when_not_rendering;
mod test_vram_access_after_scrolling;
mod test_vram_access_during_background_rendering;
mod test_vram_access_during_sprite_rendering;
mod test_vram_access_during_sprite_rendering_double_height;
mod test_vram_access_during_sprite_rendering_without_sprites;
mod test_vram_access_sprite_rendering_out_of_range;

pub use tests::test_current_address_during_background_rendering::*;
pub use tests::test_current_address_during_sprite_rendering::*;
pub use tests::test_current_address_during_sprite_rendering_without_sprites::*;
pub use tests::test_current_address_when_not_rendering::*;
pub use tests::test_vram_access_after_scrolling::*;
pub use tests::test_vram_access_during_background_rendering::*;
pub use tests::test_vram_access_during_sprite_rendering::*;
pub use tests::test_vram_access_during_sprite_rendering_double_height::*;
pub use tests::test_vram_access_during_sprite_rendering_without_sprites::*;
pub use tests::test_vram_access_sprite_rendering_out_of_range::*;

#[macro_export]
macro_rules! rp2c02_testsuite {
    ($interface:ident) => (
        mod rp2c02_testsuite {
            #[test]
            fn test_current_address_during_background_rendering() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_current_address_during_background_rendering( &mut ppu );
            }
            #[test]
            fn test_current_address_during_sprite_rendering() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_current_address_during_sprite_rendering( &mut ppu );
            }
            #[test]
            fn test_current_address_during_sprite_rendering_without_sprites() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_current_address_during_sprite_rendering_without_sprites( &mut ppu );
            }
            #[test]
            fn test_current_address_when_not_rendering() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_current_address_when_not_rendering( &mut ppu );
            }
            #[test]
            fn test_vram_access_after_scrolling() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_vram_access_after_scrolling( &mut ppu );
            }
            #[test]
            fn test_vram_access_during_background_rendering() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_vram_access_during_background_rendering( &mut ppu );
            }
            #[test]
            fn test_vram_access_during_sprite_rendering() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_vram_access_during_sprite_rendering( &mut ppu );
            }
            #[test]
            fn test_vram_access_during_sprite_rendering_double_height() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_vram_access_during_sprite_rendering_double_height( &mut ppu );
            }
            #[test]
            fn test_vram_access_during_sprite_rendering_without_sprites() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_vram_access_during_sprite_rendering_without_sprites( &mut ppu );
            }
            #[test]
            fn test_vram_access_sprite_rendering_out_of_range() {
                use super::$interface;
                let mut ppu = $interface::new();
                $crate::tests::test_vram_access_sprite_rendering_out_of_range( &mut ppu );
            }
        }
    )
}
