// This file was AUTOGENERATED; do not edit!

#[allow(unused_imports)]
use super::super::assert_eq;
use TestPPU;

#[inline(never)]
pub fn test_vram_access_sprite_rendering_out_of_range( ppu: &mut TestPPU ) {
    assert_eq!( ppu.scanline(), 261 );
    assert_eq!( ppu.dot(), 0 );
    for i in 0..4096u32 {
        ppu.write_vram( i as u16, (i + 0x80) as u8 );
    }
    for i in 0..960u32 {
        ppu.write_vram( (0x2000 + i) as u16, (i + 0x80) as u8 );
    }
    for i in 0..64u32 {
        ppu.write_vram( (0x2000 + 960 + i) as u16, (0x80 | i) as u8 );
    }
    ppu.write_ioreg( 1, 0x14 );
    ppu.step_pixel(); // 261 000 -> 261 001
    ppu.step_pixel(); // 261 001 -> 261 002
    ppu.step_pixel(); // 261 002 -> 261 003
    ppu.step_scanline();
    for _ in 0..7u32 {
        ppu.step_scanline();
    } // 006 340 -> 007 000
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 007 256 -> 007 257
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0x77 );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x01 );
    ppu.write_secondary_sprite_ram( 5, 0x88 );
    ppu.write_secondary_sprite_ram( 6, 0x00 );
    ppu.write_secondary_sprite_ram( 7, 0x00 );
    ppu.write_secondary_sprite_ram( 8, 0x07 );
    ppu.write_secondary_sprite_ram( 9, 0x99 );
    ppu.write_secondary_sprite_ram( 10, 0x00 );
    ppu.write_secondary_sprite_ram( 11, 0x00 );
    ppu.write_secondary_sprite_ram( 12, 0x08 );
    ppu.write_secondary_sprite_ram( 13, 0xAA );
    ppu.write_secondary_sprite_ram( 14, 0x00 );
    ppu.write_secondary_sprite_ram( 15, 0x00 );
    ppu.write_secondary_sprite_ram( 16, 0x09 );
    ppu.write_secondary_sprite_ram( 17, 0xBB );
    ppu.write_secondary_sprite_ram( 18, 0x00 );
    ppu.write_secondary_sprite_ram( 19, 0x00 );
    ppu.write_secondary_sprite_ram( 20, 0x0F );
    ppu.write_secondary_sprite_ram( 21, 0xCC );
    ppu.write_secondary_sprite_ram( 22, 0x00 );
    ppu.write_secondary_sprite_ram( 23, 0x00 );
    ppu.write_secondary_sprite_ram( 24, 0x10 );
    ppu.write_secondary_sprite_ram( 25, 0xDD );
    ppu.write_secondary_sprite_ram( 26, 0x00 );
    ppu.write_secondary_sprite_ram( 27, 0x00 );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xEE );
    ppu.write_secondary_sprite_ram( 30, 0x00 );
    ppu.write_secondary_sprite_ram( 31, 0x00 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 257 -> 007 258
    ppu.expect_vram_read( 0x2422, 0xA2 );
    ppu.step_pixel(); // 007 258 -> 007 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 259 -> 007 260
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 260 -> 007 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 261 -> 007 262
    ppu.expect_vram_read( 0x0777, 0xF7 );
    ppu.step_pixel(); // 007 262 -> 007 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 263 -> 007 264
    ppu.expect_vram_read( 0x077F, 0xFF );
    ppu.step_pixel(); // 007 264 -> 007 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 265 -> 007 266
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 266 -> 007 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 267 -> 007 268
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 268 -> 007 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 269 -> 007 270
    ppu.expect_vram_read( 0x0886, 0x06 );
    ppu.step_pixel(); // 007 270 -> 007 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 271 -> 007 272
    ppu.expect_vram_read( 0x088E, 0x0E );
    ppu.step_pixel(); // 007 272 -> 007 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 273 -> 007 274
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 274 -> 007 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 275 -> 007 276
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 276 -> 007 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 277 -> 007 278
    ppu.expect_vram_read( 0x0990, 0x10 );
    ppu.step_pixel(); // 007 278 -> 007 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 279 -> 007 280
    ppu.expect_vram_read( 0x0998, 0x18 );
    ppu.step_pixel(); // 007 280 -> 007 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 281 -> 007 282
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 282 -> 007 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 283 -> 007 284
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 284 -> 007 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 285 -> 007 286
    ppu.expect_vram_read( 0x0AA7, 0x27 );
    ppu.step_pixel(); // 007 286 -> 007 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 287 -> 007 288
    ppu.expect_vram_read( 0x0AAF, 0x2F );
    ppu.step_pixel(); // 007 288 -> 007 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 289 -> 007 290
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 290 -> 007 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 291 -> 007 292
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 292 -> 007 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 293 -> 007 294
    ppu.expect_vram_read( 0x0BB6, 0x36 );
    ppu.step_pixel(); // 007 294 -> 007 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 295 -> 007 296
    ppu.expect_vram_read( 0x0BBE, 0x3E );
    ppu.step_pixel(); // 007 296 -> 007 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 297 -> 007 298
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 298 -> 007 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 299 -> 007 300
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 300 -> 007 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 301 -> 007 302
    ppu.expect_vram_read( 0x0CC0, 0x40 );
    ppu.step_pixel(); // 007 302 -> 007 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 303 -> 007 304
    ppu.expect_vram_read( 0x0CC8, 0x48 );
    ppu.step_pixel(); // 007 304 -> 007 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 305 -> 007 306
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 306 -> 007 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 307 -> 007 308
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 308 -> 007 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 309 -> 007 310
    ppu.expect_vram_read( 0x0DD7, 0x57 );
    ppu.step_pixel(); // 007 310 -> 007 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 311 -> 007 312
    ppu.expect_vram_read( 0x0DDF, 0x5F );
    ppu.step_pixel(); // 007 312 -> 007 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 313 -> 007 314
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 314 -> 007 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 315 -> 007 316
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 316 -> 007 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 317 -> 007 318
    ppu.expect_vram_read( 0x0EE0, 0x60 );
    ppu.step_pixel(); // 007 318 -> 007 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 319 -> 007 320
    ppu.expect_vram_read( 0x0EE8, 0x68 );
    ppu.step_pixel(); // 007 320 -> 007 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 008 256 -> 008 257
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0x77 );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x01 );
    ppu.write_secondary_sprite_ram( 5, 0x88 );
    ppu.write_secondary_sprite_ram( 6, 0x00 );
    ppu.write_secondary_sprite_ram( 7, 0x00 );
    ppu.write_secondary_sprite_ram( 8, 0x07 );
    ppu.write_secondary_sprite_ram( 9, 0x99 );
    ppu.write_secondary_sprite_ram( 10, 0x00 );
    ppu.write_secondary_sprite_ram( 11, 0x00 );
    ppu.write_secondary_sprite_ram( 12, 0x08 );
    ppu.write_secondary_sprite_ram( 13, 0xAA );
    ppu.write_secondary_sprite_ram( 14, 0x00 );
    ppu.write_secondary_sprite_ram( 15, 0x00 );
    ppu.write_secondary_sprite_ram( 16, 0x09 );
    ppu.write_secondary_sprite_ram( 17, 0xBB );
    ppu.write_secondary_sprite_ram( 18, 0x00 );
    ppu.write_secondary_sprite_ram( 19, 0x00 );
    ppu.write_secondary_sprite_ram( 20, 0x0F );
    ppu.write_secondary_sprite_ram( 21, 0xCC );
    ppu.write_secondary_sprite_ram( 22, 0x00 );
    ppu.write_secondary_sprite_ram( 23, 0x00 );
    ppu.write_secondary_sprite_ram( 24, 0x10 );
    ppu.write_secondary_sprite_ram( 25, 0xDD );
    ppu.write_secondary_sprite_ram( 26, 0x00 );
    ppu.write_secondary_sprite_ram( 27, 0x00 );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xEE );
    ppu.write_secondary_sprite_ram( 30, 0x00 );
    ppu.write_secondary_sprite_ram( 31, 0x00 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 257 -> 008 258
    ppu.expect_vram_read( 0x2422, 0xA2 );
    ppu.step_pixel(); // 008 258 -> 008 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 259 -> 008 260
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 260 -> 008 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 261 -> 008 262
    ppu.expect_vram_read( 0x0770, 0xF0 );
    ppu.step_pixel(); // 008 262 -> 008 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 263 -> 008 264
    ppu.expect_vram_read( 0x0778, 0xF8 );
    ppu.step_pixel(); // 008 264 -> 008 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 265 -> 008 266
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 266 -> 008 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 267 -> 008 268
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 268 -> 008 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 269 -> 008 270
    ppu.expect_vram_read( 0x0887, 0x07 );
    ppu.step_pixel(); // 008 270 -> 008 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 271 -> 008 272
    ppu.expect_vram_read( 0x088F, 0x0F );
    ppu.step_pixel(); // 008 272 -> 008 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 273 -> 008 274
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 274 -> 008 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 275 -> 008 276
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 276 -> 008 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 277 -> 008 278
    ppu.expect_vram_read( 0x0991, 0x11 );
    ppu.step_pixel(); // 008 278 -> 008 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 279 -> 008 280
    ppu.expect_vram_read( 0x0999, 0x19 );
    ppu.step_pixel(); // 008 280 -> 008 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 281 -> 008 282
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 282 -> 008 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 283 -> 008 284
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 284 -> 008 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 285 -> 008 286
    ppu.expect_vram_read( 0x0AA0, 0x20 );
    ppu.step_pixel(); // 008 286 -> 008 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 287 -> 008 288
    ppu.expect_vram_read( 0x0AA8, 0x28 );
    ppu.step_pixel(); // 008 288 -> 008 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 289 -> 008 290
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 290 -> 008 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 291 -> 008 292
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 292 -> 008 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 293 -> 008 294
    ppu.expect_vram_read( 0x0BB7, 0x37 );
    ppu.step_pixel(); // 008 294 -> 008 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 295 -> 008 296
    ppu.expect_vram_read( 0x0BBF, 0x3F );
    ppu.step_pixel(); // 008 296 -> 008 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 297 -> 008 298
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 298 -> 008 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 299 -> 008 300
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 300 -> 008 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 301 -> 008 302
    ppu.expect_vram_read( 0x0CC1, 0x41 );
    ppu.step_pixel(); // 008 302 -> 008 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 303 -> 008 304
    ppu.expect_vram_read( 0x0CC9, 0x49 );
    ppu.step_pixel(); // 008 304 -> 008 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 305 -> 008 306
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 306 -> 008 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 307 -> 008 308
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 308 -> 008 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 309 -> 008 310
    ppu.expect_vram_read( 0x0DD0, 0x50 );
    ppu.step_pixel(); // 008 310 -> 008 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 311 -> 008 312
    ppu.expect_vram_read( 0x0DD8, 0x58 );
    ppu.step_pixel(); // 008 312 -> 008 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 313 -> 008 314
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 314 -> 008 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 315 -> 008 316
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 316 -> 008 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 317 -> 008 318
    ppu.expect_vram_read( 0x0EE1, 0x61 );
    ppu.step_pixel(); // 008 318 -> 008 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 319 -> 008 320
    ppu.expect_vram_read( 0x0EE9, 0x69 );
    ppu.step_pixel(); // 008 320 -> 008 321
    ppu.step_scanline();
    assert_eq!( ppu.scanline(), 9 );
    assert_eq!( ppu.dot(), 0 );
}
