// This file was AUTOGENERATED; do not edit!

#[allow(unused_imports)]
use super::super::assert_eq;
use TestPPU;

#[inline(never)]
pub fn test_vram_access_during_sprite_rendering( ppu: &mut TestPPU ) {
    assert_eq!( ppu.scanline(), 261 );
    assert_eq!( ppu.dot(), 0 );
    for i in 0..4096u32 {
        ppu.write_vram( i as u16, (i + 0x80) as u8 );
    }
    for i in 0..960u32 {
        ppu.write_vram( (0x2000 + i) as u16, (i + 0x80) as u8 );
    }
    for i in 0..64u32 {
        ppu.write_vram( (0x2000 + 960 + i) as u16, (0x80 | i) as u8 );
    }
    ppu.write_ioreg( 1, 0x14 );
    ppu.step_pixel(); // 261 000 -> 261 001
    ppu.step_pixel(); // 261 001 -> 261 002
    ppu.step_pixel(); // 261 002 -> 261 003
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 000 256 -> 000 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 257 -> 000 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 000 258 -> 000 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 259 -> 000 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 260 -> 000 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 261 -> 000 262
    ppu.expect_vram_read( 0x0AA0, 0x20 );
    ppu.step_pixel(); // 000 262 -> 000 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 263 -> 000 264
    ppu.expect_vram_read( 0x0AA8, 0x28 );
    ppu.step_pixel(); // 000 264 -> 000 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 265 -> 000 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 266 -> 000 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 267 -> 000 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 268 -> 000 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 269 -> 000 270
    ppu.expect_vram_read( 0x0BA0, 0x20 );
    ppu.step_pixel(); // 000 270 -> 000 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 271 -> 000 272
    ppu.expect_vram_read( 0x0BA8, 0x28 );
    ppu.step_pixel(); // 000 272 -> 000 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 273 -> 000 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 274 -> 000 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 275 -> 000 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 276 -> 000 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 277 -> 000 278
    ppu.expect_vram_read( 0x0CA7, 0x27 );
    ppu.step_pixel(); // 000 278 -> 000 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 279 -> 000 280
    ppu.expect_vram_read( 0x0CAF, 0x2F );
    ppu.step_pixel(); // 000 280 -> 000 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 281 -> 000 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 282 -> 000 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 283 -> 000 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 284 -> 000 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 285 -> 000 286
    ppu.expect_vram_read( 0x0DA7, 0x27 );
    ppu.step_pixel(); // 000 286 -> 000 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 287 -> 000 288
    ppu.expect_vram_read( 0x0DAF, 0x2F );
    ppu.step_pixel(); // 000 288 -> 000 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 289 -> 000 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 290 -> 000 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 291 -> 000 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 292 -> 000 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 293 -> 000 294
    ppu.expect_vram_read( 0x0FF6, 0x76 );
    ppu.step_pixel(); // 000 294 -> 000 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 295 -> 000 296
    ppu.expect_vram_read( 0x0FFE, 0x7E );
    ppu.step_pixel(); // 000 296 -> 000 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 297 -> 000 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 298 -> 000 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 299 -> 000 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 300 -> 000 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 301 -> 000 302
    ppu.expect_vram_read( 0x0FF6, 0x76 );
    ppu.step_pixel(); // 000 302 -> 000 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 303 -> 000 304
    ppu.expect_vram_read( 0x0FFE, 0x7E );
    ppu.step_pixel(); // 000 304 -> 000 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 305 -> 000 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 306 -> 000 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 307 -> 000 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 308 -> 000 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 309 -> 000 310
    ppu.expect_vram_read( 0x0FF6, 0x76 );
    ppu.step_pixel(); // 000 310 -> 000 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 311 -> 000 312
    ppu.expect_vram_read( 0x0FFE, 0x7E );
    ppu.step_pixel(); // 000 312 -> 000 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 313 -> 000 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 314 -> 000 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 315 -> 000 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 316 -> 000 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 317 -> 000 318
    ppu.expect_vram_read( 0x0FF6, 0x76 );
    ppu.step_pixel(); // 000 318 -> 000 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 319 -> 000 320
    ppu.expect_vram_read( 0x0FFE, 0x7E );
    ppu.step_pixel(); // 000 320 -> 000 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 001 256 -> 001 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 257 -> 001 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 001 258 -> 001 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 259 -> 001 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 260 -> 001 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 261 -> 001 262
    ppu.expect_vram_read( 0x0AA1, 0x21 );
    ppu.step_pixel(); // 001 262 -> 001 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 263 -> 001 264
    ppu.expect_vram_read( 0x0AA9, 0x29 );
    ppu.step_pixel(); // 001 264 -> 001 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 265 -> 001 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 266 -> 001 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 267 -> 001 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 268 -> 001 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 269 -> 001 270
    ppu.expect_vram_read( 0x0BA1, 0x21 );
    ppu.step_pixel(); // 001 270 -> 001 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 271 -> 001 272
    ppu.expect_vram_read( 0x0BA9, 0x29 );
    ppu.step_pixel(); // 001 272 -> 001 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 273 -> 001 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 274 -> 001 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 275 -> 001 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 276 -> 001 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 277 -> 001 278
    ppu.expect_vram_read( 0x0CA6, 0x26 );
    ppu.step_pixel(); // 001 278 -> 001 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 279 -> 001 280
    ppu.expect_vram_read( 0x0CAE, 0x2E );
    ppu.step_pixel(); // 001 280 -> 001 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 281 -> 001 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 282 -> 001 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 283 -> 001 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 284 -> 001 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 285 -> 001 286
    ppu.expect_vram_read( 0x0DA6, 0x26 );
    ppu.step_pixel(); // 001 286 -> 001 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 287 -> 001 288
    ppu.expect_vram_read( 0x0DAE, 0x2E );
    ppu.step_pixel(); // 001 288 -> 001 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 289 -> 001 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 290 -> 001 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 291 -> 001 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 292 -> 001 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 293 -> 001 294
    ppu.expect_vram_read( 0x0FF5, 0x75 );
    ppu.step_pixel(); // 001 294 -> 001 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 295 -> 001 296
    ppu.expect_vram_read( 0x0FFD, 0x7D );
    ppu.step_pixel(); // 001 296 -> 001 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 297 -> 001 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 298 -> 001 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 299 -> 001 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 300 -> 001 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 301 -> 001 302
    ppu.expect_vram_read( 0x0FF5, 0x75 );
    ppu.step_pixel(); // 001 302 -> 001 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 303 -> 001 304
    ppu.expect_vram_read( 0x0FFD, 0x7D );
    ppu.step_pixel(); // 001 304 -> 001 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 305 -> 001 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 306 -> 001 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 307 -> 001 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 308 -> 001 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 309 -> 001 310
    ppu.expect_vram_read( 0x0FF5, 0x75 );
    ppu.step_pixel(); // 001 310 -> 001 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 311 -> 001 312
    ppu.expect_vram_read( 0x0FFD, 0x7D );
    ppu.step_pixel(); // 001 312 -> 001 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 313 -> 001 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 314 -> 001 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 315 -> 001 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 316 -> 001 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 317 -> 001 318
    ppu.expect_vram_read( 0x0FF5, 0x75 );
    ppu.step_pixel(); // 001 318 -> 001 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 319 -> 001 320
    ppu.expect_vram_read( 0x0FFD, 0x7D );
    ppu.step_pixel(); // 001 320 -> 001 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 002 256 -> 002 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 257 -> 002 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 002 258 -> 002 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 259 -> 002 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 260 -> 002 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 261 -> 002 262
    ppu.expect_vram_read( 0x0AA2, 0x22 );
    ppu.step_pixel(); // 002 262 -> 002 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 263 -> 002 264
    ppu.expect_vram_read( 0x0AAA, 0x2A );
    ppu.step_pixel(); // 002 264 -> 002 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 265 -> 002 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 266 -> 002 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 267 -> 002 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 268 -> 002 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 269 -> 002 270
    ppu.expect_vram_read( 0x0BA2, 0x22 );
    ppu.step_pixel(); // 002 270 -> 002 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 271 -> 002 272
    ppu.expect_vram_read( 0x0BAA, 0x2A );
    ppu.step_pixel(); // 002 272 -> 002 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 273 -> 002 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 274 -> 002 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 275 -> 002 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 276 -> 002 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 277 -> 002 278
    ppu.expect_vram_read( 0x0CA5, 0x25 );
    ppu.step_pixel(); // 002 278 -> 002 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 279 -> 002 280
    ppu.expect_vram_read( 0x0CAD, 0x2D );
    ppu.step_pixel(); // 002 280 -> 002 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 281 -> 002 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 282 -> 002 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 283 -> 002 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 284 -> 002 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 285 -> 002 286
    ppu.expect_vram_read( 0x0DA5, 0x25 );
    ppu.step_pixel(); // 002 286 -> 002 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 287 -> 002 288
    ppu.expect_vram_read( 0x0DAD, 0x2D );
    ppu.step_pixel(); // 002 288 -> 002 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 289 -> 002 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 290 -> 002 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 291 -> 002 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 292 -> 002 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 293 -> 002 294
    ppu.expect_vram_read( 0x0FF4, 0x74 );
    ppu.step_pixel(); // 002 294 -> 002 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 295 -> 002 296
    ppu.expect_vram_read( 0x0FFC, 0x7C );
    ppu.step_pixel(); // 002 296 -> 002 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 297 -> 002 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 298 -> 002 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 299 -> 002 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 300 -> 002 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 301 -> 002 302
    ppu.expect_vram_read( 0x0FF4, 0x74 );
    ppu.step_pixel(); // 002 302 -> 002 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 303 -> 002 304
    ppu.expect_vram_read( 0x0FFC, 0x7C );
    ppu.step_pixel(); // 002 304 -> 002 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 305 -> 002 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 306 -> 002 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 307 -> 002 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 308 -> 002 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 309 -> 002 310
    ppu.expect_vram_read( 0x0FF4, 0x74 );
    ppu.step_pixel(); // 002 310 -> 002 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 311 -> 002 312
    ppu.expect_vram_read( 0x0FFC, 0x7C );
    ppu.step_pixel(); // 002 312 -> 002 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 313 -> 002 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 314 -> 002 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 315 -> 002 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 316 -> 002 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 317 -> 002 318
    ppu.expect_vram_read( 0x0FF4, 0x74 );
    ppu.step_pixel(); // 002 318 -> 002 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 319 -> 002 320
    ppu.expect_vram_read( 0x0FFC, 0x7C );
    ppu.step_pixel(); // 002 320 -> 002 321
    ppu.step_scanline();
    assert_eq!( ppu.scanline(), 3 );
    assert_eq!( ppu.dot(), 0 );
}
