// This file was AUTOGENERATED; do not edit!

#[allow(unused_imports)]
use super::super::assert_eq;
use TestPPU;

#[inline(never)]
pub fn test_vram_access_during_sprite_rendering_double_height( ppu: &mut TestPPU ) {
    assert_eq!( ppu.scanline(), 261 );
    assert_eq!( ppu.dot(), 0 );
    for i in 0..4096u32 {
        ppu.write_vram( i as u16, (i + 0x80) as u8 );
    }
    for i in 0..960u32 {
        ppu.write_vram( (0x2000 + i) as u16, (i + 0x80) as u8 );
    }
    for i in 0..64u32 {
        ppu.write_vram( (0x2000 + 960 + i) as u16, (0x80 | i) as u8 );
    }
    ppu.write_ioreg( 1, 0x14 );
    ppu.step_pixel(); // 261 000 -> 261 001
    ppu.step_pixel(); // 261 001 -> 261 002
    ppu.step_pixel(); // 261 002 -> 261 003
    ppu.write_ioreg( 0, 0x20 );
    ppu.step_pixel(); // 261 003 -> 261 004
    ppu.step_pixel(); // 261 004 -> 261 005
    ppu.step_pixel(); // 261 005 -> 261 006
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 000 256 -> 000 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 257 -> 000 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 000 258 -> 000 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 259 -> 000 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 260 -> 000 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 261 -> 000 262
    ppu.expect_vram_read( 0x0AA0, 0x20 );
    ppu.step_pixel(); // 000 262 -> 000 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 263 -> 000 264
    ppu.expect_vram_read( 0x0AA8, 0x28 );
    ppu.step_pixel(); // 000 264 -> 000 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 265 -> 000 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 266 -> 000 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 267 -> 000 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 268 -> 000 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 269 -> 000 270
    ppu.expect_vram_read( 0x0BA0, 0x20 );
    ppu.step_pixel(); // 000 270 -> 000 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 271 -> 000 272
    ppu.expect_vram_read( 0x0BA8, 0x28 );
    ppu.step_pixel(); // 000 272 -> 000 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 273 -> 000 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 274 -> 000 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 275 -> 000 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 276 -> 000 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 277 -> 000 278
    ppu.expect_vram_read( 0x0CB7, 0x37 );
    ppu.step_pixel(); // 000 278 -> 000 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 279 -> 000 280
    ppu.expect_vram_read( 0x0CBF, 0x3F );
    ppu.step_pixel(); // 000 280 -> 000 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 281 -> 000 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 282 -> 000 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 283 -> 000 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 284 -> 000 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 285 -> 000 286
    ppu.expect_vram_read( 0x0DB7, 0x37 );
    ppu.step_pixel(); // 000 286 -> 000 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 287 -> 000 288
    ppu.expect_vram_read( 0x0DBF, 0x3F );
    ppu.step_pixel(); // 000 288 -> 000 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 289 -> 000 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 290 -> 000 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 291 -> 000 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 292 -> 000 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 293 -> 000 294
    ppu.expect_vram_read( 0x1FF6, 0x76 );
    ppu.step_pixel(); // 000 294 -> 000 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 295 -> 000 296
    ppu.expect_vram_read( 0x1FFE, 0x7E );
    ppu.step_pixel(); // 000 296 -> 000 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 297 -> 000 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 298 -> 000 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 299 -> 000 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 300 -> 000 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 301 -> 000 302
    ppu.expect_vram_read( 0x1FF6, 0x76 );
    ppu.step_pixel(); // 000 302 -> 000 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 303 -> 000 304
    ppu.expect_vram_read( 0x1FFE, 0x7E );
    ppu.step_pixel(); // 000 304 -> 000 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 305 -> 000 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 306 -> 000 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 307 -> 000 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 308 -> 000 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 309 -> 000 310
    ppu.expect_vram_read( 0x1FF6, 0x76 );
    ppu.step_pixel(); // 000 310 -> 000 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 311 -> 000 312
    ppu.expect_vram_read( 0x1FFE, 0x7E );
    ppu.step_pixel(); // 000 312 -> 000 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 313 -> 000 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 314 -> 000 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 315 -> 000 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 000 316 -> 000 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 317 -> 000 318
    ppu.expect_vram_read( 0x1FF6, 0x76 );
    ppu.step_pixel(); // 000 318 -> 000 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 000 319 -> 000 320
    ppu.expect_vram_read( 0x1FFE, 0x7E );
    ppu.step_pixel(); // 000 320 -> 000 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 001 256 -> 001 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 257 -> 001 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 001 258 -> 001 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 259 -> 001 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 260 -> 001 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 261 -> 001 262
    ppu.expect_vram_read( 0x0AA1, 0x21 );
    ppu.step_pixel(); // 001 262 -> 001 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 263 -> 001 264
    ppu.expect_vram_read( 0x0AA9, 0x29 );
    ppu.step_pixel(); // 001 264 -> 001 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 265 -> 001 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 266 -> 001 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 267 -> 001 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 268 -> 001 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 269 -> 001 270
    ppu.expect_vram_read( 0x0BA1, 0x21 );
    ppu.step_pixel(); // 001 270 -> 001 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 271 -> 001 272
    ppu.expect_vram_read( 0x0BA9, 0x29 );
    ppu.step_pixel(); // 001 272 -> 001 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 273 -> 001 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 274 -> 001 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 275 -> 001 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 276 -> 001 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 277 -> 001 278
    ppu.expect_vram_read( 0x0CB6, 0x36 );
    ppu.step_pixel(); // 001 278 -> 001 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 279 -> 001 280
    ppu.expect_vram_read( 0x0CBE, 0x3E );
    ppu.step_pixel(); // 001 280 -> 001 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 281 -> 001 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 282 -> 001 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 283 -> 001 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 284 -> 001 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 285 -> 001 286
    ppu.expect_vram_read( 0x0DB6, 0x36 );
    ppu.step_pixel(); // 001 286 -> 001 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 287 -> 001 288
    ppu.expect_vram_read( 0x0DBE, 0x3E );
    ppu.step_pixel(); // 001 288 -> 001 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 289 -> 001 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 290 -> 001 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 291 -> 001 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 292 -> 001 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 293 -> 001 294
    ppu.expect_vram_read( 0x1FF5, 0x75 );
    ppu.step_pixel(); // 001 294 -> 001 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 295 -> 001 296
    ppu.expect_vram_read( 0x1FFD, 0x7D );
    ppu.step_pixel(); // 001 296 -> 001 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 297 -> 001 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 298 -> 001 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 299 -> 001 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 300 -> 001 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 301 -> 001 302
    ppu.expect_vram_read( 0x1FF5, 0x75 );
    ppu.step_pixel(); // 001 302 -> 001 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 303 -> 001 304
    ppu.expect_vram_read( 0x1FFD, 0x7D );
    ppu.step_pixel(); // 001 304 -> 001 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 305 -> 001 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 306 -> 001 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 307 -> 001 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 308 -> 001 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 309 -> 001 310
    ppu.expect_vram_read( 0x1FF5, 0x75 );
    ppu.step_pixel(); // 001 310 -> 001 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 311 -> 001 312
    ppu.expect_vram_read( 0x1FFD, 0x7D );
    ppu.step_pixel(); // 001 312 -> 001 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 313 -> 001 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 314 -> 001 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 315 -> 001 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 001 316 -> 001 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 317 -> 001 318
    ppu.expect_vram_read( 0x1FF5, 0x75 );
    ppu.step_pixel(); // 001 318 -> 001 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 001 319 -> 001 320
    ppu.expect_vram_read( 0x1FFD, 0x7D );
    ppu.step_pixel(); // 001 320 -> 001 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 002 256 -> 002 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 257 -> 002 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 002 258 -> 002 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 259 -> 002 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 260 -> 002 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 261 -> 002 262
    ppu.expect_vram_read( 0x0AA2, 0x22 );
    ppu.step_pixel(); // 002 262 -> 002 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 263 -> 002 264
    ppu.expect_vram_read( 0x0AAA, 0x2A );
    ppu.step_pixel(); // 002 264 -> 002 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 265 -> 002 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 266 -> 002 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 267 -> 002 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 268 -> 002 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 269 -> 002 270
    ppu.expect_vram_read( 0x0BA2, 0x22 );
    ppu.step_pixel(); // 002 270 -> 002 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 271 -> 002 272
    ppu.expect_vram_read( 0x0BAA, 0x2A );
    ppu.step_pixel(); // 002 272 -> 002 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 273 -> 002 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 274 -> 002 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 275 -> 002 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 276 -> 002 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 277 -> 002 278
    ppu.expect_vram_read( 0x0CB5, 0x35 );
    ppu.step_pixel(); // 002 278 -> 002 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 279 -> 002 280
    ppu.expect_vram_read( 0x0CBD, 0x3D );
    ppu.step_pixel(); // 002 280 -> 002 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 281 -> 002 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 282 -> 002 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 283 -> 002 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 284 -> 002 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 285 -> 002 286
    ppu.expect_vram_read( 0x0DB5, 0x35 );
    ppu.step_pixel(); // 002 286 -> 002 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 287 -> 002 288
    ppu.expect_vram_read( 0x0DBD, 0x3D );
    ppu.step_pixel(); // 002 288 -> 002 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 289 -> 002 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 290 -> 002 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 291 -> 002 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 292 -> 002 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 293 -> 002 294
    ppu.expect_vram_read( 0x1FF4, 0x74 );
    ppu.step_pixel(); // 002 294 -> 002 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 295 -> 002 296
    ppu.expect_vram_read( 0x1FFC, 0x7C );
    ppu.step_pixel(); // 002 296 -> 002 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 297 -> 002 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 298 -> 002 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 299 -> 002 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 300 -> 002 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 301 -> 002 302
    ppu.expect_vram_read( 0x1FF4, 0x74 );
    ppu.step_pixel(); // 002 302 -> 002 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 303 -> 002 304
    ppu.expect_vram_read( 0x1FFC, 0x7C );
    ppu.step_pixel(); // 002 304 -> 002 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 305 -> 002 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 306 -> 002 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 307 -> 002 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 308 -> 002 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 309 -> 002 310
    ppu.expect_vram_read( 0x1FF4, 0x74 );
    ppu.step_pixel(); // 002 310 -> 002 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 311 -> 002 312
    ppu.expect_vram_read( 0x1FFC, 0x7C );
    ppu.step_pixel(); // 002 312 -> 002 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 313 -> 002 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 314 -> 002 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 315 -> 002 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 002 316 -> 002 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 317 -> 002 318
    ppu.expect_vram_read( 0x1FF4, 0x74 );
    ppu.step_pixel(); // 002 318 -> 002 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 002 319 -> 002 320
    ppu.expect_vram_read( 0x1FFC, 0x7C );
    ppu.step_pixel(); // 002 320 -> 002 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 003 256 -> 003 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 257 -> 003 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 003 258 -> 003 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 259 -> 003 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 260 -> 003 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 261 -> 003 262
    ppu.expect_vram_read( 0x0AA3, 0x23 );
    ppu.step_pixel(); // 003 262 -> 003 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 263 -> 003 264
    ppu.expect_vram_read( 0x0AAB, 0x2B );
    ppu.step_pixel(); // 003 264 -> 003 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 265 -> 003 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 266 -> 003 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 267 -> 003 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 268 -> 003 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 269 -> 003 270
    ppu.expect_vram_read( 0x0BA3, 0x23 );
    ppu.step_pixel(); // 003 270 -> 003 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 271 -> 003 272
    ppu.expect_vram_read( 0x0BAB, 0x2B );
    ppu.step_pixel(); // 003 272 -> 003 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 273 -> 003 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 274 -> 003 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 275 -> 003 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 276 -> 003 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 277 -> 003 278
    ppu.expect_vram_read( 0x0CB4, 0x34 );
    ppu.step_pixel(); // 003 278 -> 003 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 279 -> 003 280
    ppu.expect_vram_read( 0x0CBC, 0x3C );
    ppu.step_pixel(); // 003 280 -> 003 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 281 -> 003 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 282 -> 003 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 283 -> 003 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 284 -> 003 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 285 -> 003 286
    ppu.expect_vram_read( 0x0DB4, 0x34 );
    ppu.step_pixel(); // 003 286 -> 003 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 287 -> 003 288
    ppu.expect_vram_read( 0x0DBC, 0x3C );
    ppu.step_pixel(); // 003 288 -> 003 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 289 -> 003 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 290 -> 003 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 291 -> 003 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 292 -> 003 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 293 -> 003 294
    ppu.expect_vram_read( 0x1FF3, 0x73 );
    ppu.step_pixel(); // 003 294 -> 003 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 295 -> 003 296
    ppu.expect_vram_read( 0x1FFB, 0x7B );
    ppu.step_pixel(); // 003 296 -> 003 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 297 -> 003 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 298 -> 003 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 299 -> 003 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 300 -> 003 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 301 -> 003 302
    ppu.expect_vram_read( 0x1FF3, 0x73 );
    ppu.step_pixel(); // 003 302 -> 003 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 303 -> 003 304
    ppu.expect_vram_read( 0x1FFB, 0x7B );
    ppu.step_pixel(); // 003 304 -> 003 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 305 -> 003 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 306 -> 003 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 307 -> 003 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 308 -> 003 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 309 -> 003 310
    ppu.expect_vram_read( 0x1FF3, 0x73 );
    ppu.step_pixel(); // 003 310 -> 003 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 311 -> 003 312
    ppu.expect_vram_read( 0x1FFB, 0x7B );
    ppu.step_pixel(); // 003 312 -> 003 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 313 -> 003 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 314 -> 003 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 315 -> 003 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 003 316 -> 003 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 317 -> 003 318
    ppu.expect_vram_read( 0x1FF3, 0x73 );
    ppu.step_pixel(); // 003 318 -> 003 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 003 319 -> 003 320
    ppu.expect_vram_read( 0x1FFB, 0x7B );
    ppu.step_pixel(); // 003 320 -> 003 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 004 256 -> 004 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 257 -> 004 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 004 258 -> 004 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 259 -> 004 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 260 -> 004 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 261 -> 004 262
    ppu.expect_vram_read( 0x0AA4, 0x24 );
    ppu.step_pixel(); // 004 262 -> 004 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 263 -> 004 264
    ppu.expect_vram_read( 0x0AAC, 0x2C );
    ppu.step_pixel(); // 004 264 -> 004 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 265 -> 004 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 266 -> 004 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 267 -> 004 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 268 -> 004 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 269 -> 004 270
    ppu.expect_vram_read( 0x0BA4, 0x24 );
    ppu.step_pixel(); // 004 270 -> 004 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 271 -> 004 272
    ppu.expect_vram_read( 0x0BAC, 0x2C );
    ppu.step_pixel(); // 004 272 -> 004 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 273 -> 004 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 274 -> 004 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 275 -> 004 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 276 -> 004 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 277 -> 004 278
    ppu.expect_vram_read( 0x0CB3, 0x33 );
    ppu.step_pixel(); // 004 278 -> 004 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 279 -> 004 280
    ppu.expect_vram_read( 0x0CBB, 0x3B );
    ppu.step_pixel(); // 004 280 -> 004 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 281 -> 004 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 282 -> 004 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 283 -> 004 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 284 -> 004 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 285 -> 004 286
    ppu.expect_vram_read( 0x0DB3, 0x33 );
    ppu.step_pixel(); // 004 286 -> 004 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 287 -> 004 288
    ppu.expect_vram_read( 0x0DBB, 0x3B );
    ppu.step_pixel(); // 004 288 -> 004 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 289 -> 004 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 290 -> 004 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 291 -> 004 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 292 -> 004 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 293 -> 004 294
    ppu.expect_vram_read( 0x1FF2, 0x72 );
    ppu.step_pixel(); // 004 294 -> 004 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 295 -> 004 296
    ppu.expect_vram_read( 0x1FFA, 0x7A );
    ppu.step_pixel(); // 004 296 -> 004 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 297 -> 004 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 298 -> 004 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 299 -> 004 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 300 -> 004 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 301 -> 004 302
    ppu.expect_vram_read( 0x1FF2, 0x72 );
    ppu.step_pixel(); // 004 302 -> 004 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 303 -> 004 304
    ppu.expect_vram_read( 0x1FFA, 0x7A );
    ppu.step_pixel(); // 004 304 -> 004 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 305 -> 004 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 306 -> 004 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 307 -> 004 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 308 -> 004 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 309 -> 004 310
    ppu.expect_vram_read( 0x1FF2, 0x72 );
    ppu.step_pixel(); // 004 310 -> 004 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 311 -> 004 312
    ppu.expect_vram_read( 0x1FFA, 0x7A );
    ppu.step_pixel(); // 004 312 -> 004 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 313 -> 004 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 314 -> 004 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 315 -> 004 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 004 316 -> 004 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 317 -> 004 318
    ppu.expect_vram_read( 0x1FF2, 0x72 );
    ppu.step_pixel(); // 004 318 -> 004 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 004 319 -> 004 320
    ppu.expect_vram_read( 0x1FFA, 0x7A );
    ppu.step_pixel(); // 004 320 -> 004 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 005 256 -> 005 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 257 -> 005 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 005 258 -> 005 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 259 -> 005 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 260 -> 005 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 261 -> 005 262
    ppu.expect_vram_read( 0x0AA5, 0x25 );
    ppu.step_pixel(); // 005 262 -> 005 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 263 -> 005 264
    ppu.expect_vram_read( 0x0AAD, 0x2D );
    ppu.step_pixel(); // 005 264 -> 005 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 265 -> 005 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 266 -> 005 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 267 -> 005 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 268 -> 005 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 269 -> 005 270
    ppu.expect_vram_read( 0x0BA5, 0x25 );
    ppu.step_pixel(); // 005 270 -> 005 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 271 -> 005 272
    ppu.expect_vram_read( 0x0BAD, 0x2D );
    ppu.step_pixel(); // 005 272 -> 005 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 273 -> 005 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 274 -> 005 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 275 -> 005 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 276 -> 005 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 277 -> 005 278
    ppu.expect_vram_read( 0x0CB2, 0x32 );
    ppu.step_pixel(); // 005 278 -> 005 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 279 -> 005 280
    ppu.expect_vram_read( 0x0CBA, 0x3A );
    ppu.step_pixel(); // 005 280 -> 005 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 281 -> 005 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 282 -> 005 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 283 -> 005 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 284 -> 005 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 285 -> 005 286
    ppu.expect_vram_read( 0x0DB2, 0x32 );
    ppu.step_pixel(); // 005 286 -> 005 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 287 -> 005 288
    ppu.expect_vram_read( 0x0DBA, 0x3A );
    ppu.step_pixel(); // 005 288 -> 005 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 289 -> 005 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 290 -> 005 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 291 -> 005 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 292 -> 005 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 293 -> 005 294
    ppu.expect_vram_read( 0x1FF1, 0x71 );
    ppu.step_pixel(); // 005 294 -> 005 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 295 -> 005 296
    ppu.expect_vram_read( 0x1FF9, 0x79 );
    ppu.step_pixel(); // 005 296 -> 005 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 297 -> 005 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 298 -> 005 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 299 -> 005 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 300 -> 005 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 301 -> 005 302
    ppu.expect_vram_read( 0x1FF1, 0x71 );
    ppu.step_pixel(); // 005 302 -> 005 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 303 -> 005 304
    ppu.expect_vram_read( 0x1FF9, 0x79 );
    ppu.step_pixel(); // 005 304 -> 005 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 305 -> 005 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 306 -> 005 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 307 -> 005 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 308 -> 005 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 309 -> 005 310
    ppu.expect_vram_read( 0x1FF1, 0x71 );
    ppu.step_pixel(); // 005 310 -> 005 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 311 -> 005 312
    ppu.expect_vram_read( 0x1FF9, 0x79 );
    ppu.step_pixel(); // 005 312 -> 005 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 313 -> 005 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 314 -> 005 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 315 -> 005 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 005 316 -> 005 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 317 -> 005 318
    ppu.expect_vram_read( 0x1FF1, 0x71 );
    ppu.step_pixel(); // 005 318 -> 005 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 005 319 -> 005 320
    ppu.expect_vram_read( 0x1FF9, 0x79 );
    ppu.step_pixel(); // 005 320 -> 005 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 006 256 -> 006 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 257 -> 006 258
    ppu.expect_vram_read( 0x2402, 0x82 );
    ppu.step_pixel(); // 006 258 -> 006 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 259 -> 006 260
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 260 -> 006 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 261 -> 006 262
    ppu.expect_vram_read( 0x0AA6, 0x26 );
    ppu.step_pixel(); // 006 262 -> 006 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 263 -> 006 264
    ppu.expect_vram_read( 0x0AAE, 0x2E );
    ppu.step_pixel(); // 006 264 -> 006 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 265 -> 006 266
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 266 -> 006 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 267 -> 006 268
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 268 -> 006 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 269 -> 006 270
    ppu.expect_vram_read( 0x0BA6, 0x26 );
    ppu.step_pixel(); // 006 270 -> 006 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 271 -> 006 272
    ppu.expect_vram_read( 0x0BAE, 0x2E );
    ppu.step_pixel(); // 006 272 -> 006 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 273 -> 006 274
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 274 -> 006 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 275 -> 006 276
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 276 -> 006 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 277 -> 006 278
    ppu.expect_vram_read( 0x0CB1, 0x31 );
    ppu.step_pixel(); // 006 278 -> 006 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 279 -> 006 280
    ppu.expect_vram_read( 0x0CB9, 0x39 );
    ppu.step_pixel(); // 006 280 -> 006 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 281 -> 006 282
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 282 -> 006 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 283 -> 006 284
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 284 -> 006 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 285 -> 006 286
    ppu.expect_vram_read( 0x0DB1, 0x31 );
    ppu.step_pixel(); // 006 286 -> 006 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 287 -> 006 288
    ppu.expect_vram_read( 0x0DB9, 0x39 );
    ppu.step_pixel(); // 006 288 -> 006 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 289 -> 006 290
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 290 -> 006 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 291 -> 006 292
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 292 -> 006 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 293 -> 006 294
    ppu.expect_vram_read( 0x1FF0, 0x70 );
    ppu.step_pixel(); // 006 294 -> 006 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 295 -> 006 296
    ppu.expect_vram_read( 0x1FF8, 0x78 );
    ppu.step_pixel(); // 006 296 -> 006 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 297 -> 006 298
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 298 -> 006 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 299 -> 006 300
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 300 -> 006 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 301 -> 006 302
    ppu.expect_vram_read( 0x1FF0, 0x70 );
    ppu.step_pixel(); // 006 302 -> 006 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 303 -> 006 304
    ppu.expect_vram_read( 0x1FF8, 0x78 );
    ppu.step_pixel(); // 006 304 -> 006 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 305 -> 006 306
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 306 -> 006 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 307 -> 006 308
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 308 -> 006 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 309 -> 006 310
    ppu.expect_vram_read( 0x1FF0, 0x70 );
    ppu.step_pixel(); // 006 310 -> 006 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 311 -> 006 312
    ppu.expect_vram_read( 0x1FF8, 0x78 );
    ppu.step_pixel(); // 006 312 -> 006 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 313 -> 006 314
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 314 -> 006 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 315 -> 006 316
    ppu.expect_vram_read( 0x2000, 0x80 );
    ppu.step_pixel(); // 006 316 -> 006 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 317 -> 006 318
    ppu.expect_vram_read( 0x1FF0, 0x70 );
    ppu.step_pixel(); // 006 318 -> 006 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 006 319 -> 006 320
    ppu.expect_vram_read( 0x1FF8, 0x78 );
    ppu.step_pixel(); // 006 320 -> 006 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 007 256 -> 007 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 257 -> 007 258
    ppu.expect_vram_read( 0x2422, 0xA2 );
    ppu.step_pixel(); // 007 258 -> 007 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 259 -> 007 260
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 260 -> 007 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 261 -> 007 262
    ppu.expect_vram_read( 0x0AA7, 0x27 );
    ppu.step_pixel(); // 007 262 -> 007 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 263 -> 007 264
    ppu.expect_vram_read( 0x0AAF, 0x2F );
    ppu.step_pixel(); // 007 264 -> 007 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 265 -> 007 266
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 266 -> 007 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 267 -> 007 268
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 268 -> 007 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 269 -> 007 270
    ppu.expect_vram_read( 0x0BA7, 0x27 );
    ppu.step_pixel(); // 007 270 -> 007 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 271 -> 007 272
    ppu.expect_vram_read( 0x0BAF, 0x2F );
    ppu.step_pixel(); // 007 272 -> 007 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 273 -> 007 274
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 274 -> 007 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 275 -> 007 276
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 276 -> 007 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 277 -> 007 278
    ppu.expect_vram_read( 0x0CB0, 0x30 );
    ppu.step_pixel(); // 007 278 -> 007 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 279 -> 007 280
    ppu.expect_vram_read( 0x0CB8, 0x38 );
    ppu.step_pixel(); // 007 280 -> 007 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 281 -> 007 282
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 282 -> 007 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 283 -> 007 284
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 284 -> 007 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 285 -> 007 286
    ppu.expect_vram_read( 0x0DB0, 0x30 );
    ppu.step_pixel(); // 007 286 -> 007 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 287 -> 007 288
    ppu.expect_vram_read( 0x0DB8, 0x38 );
    ppu.step_pixel(); // 007 288 -> 007 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 289 -> 007 290
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 290 -> 007 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 291 -> 007 292
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 292 -> 007 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 293 -> 007 294
    ppu.expect_vram_read( 0x1FE7, 0x67 );
    ppu.step_pixel(); // 007 294 -> 007 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 295 -> 007 296
    ppu.expect_vram_read( 0x1FEF, 0x6F );
    ppu.step_pixel(); // 007 296 -> 007 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 297 -> 007 298
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 298 -> 007 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 299 -> 007 300
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 300 -> 007 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 301 -> 007 302
    ppu.expect_vram_read( 0x1FE7, 0x67 );
    ppu.step_pixel(); // 007 302 -> 007 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 303 -> 007 304
    ppu.expect_vram_read( 0x1FEF, 0x6F );
    ppu.step_pixel(); // 007 304 -> 007 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 305 -> 007 306
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 306 -> 007 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 307 -> 007 308
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 308 -> 007 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 309 -> 007 310
    ppu.expect_vram_read( 0x1FE7, 0x67 );
    ppu.step_pixel(); // 007 310 -> 007 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 311 -> 007 312
    ppu.expect_vram_read( 0x1FEF, 0x6F );
    ppu.step_pixel(); // 007 312 -> 007 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 313 -> 007 314
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 314 -> 007 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 315 -> 007 316
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 007 316 -> 007 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 317 -> 007 318
    ppu.expect_vram_read( 0x1FE7, 0x67 );
    ppu.step_pixel(); // 007 318 -> 007 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 007 319 -> 007 320
    ppu.expect_vram_read( 0x1FEF, 0x6F );
    ppu.step_pixel(); // 007 320 -> 007 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 008 256 -> 008 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 257 -> 008 258
    ppu.expect_vram_read( 0x2422, 0xA2 );
    ppu.step_pixel(); // 008 258 -> 008 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 259 -> 008 260
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 260 -> 008 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 261 -> 008 262
    ppu.expect_vram_read( 0x0AB0, 0x30 );
    ppu.step_pixel(); // 008 262 -> 008 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 263 -> 008 264
    ppu.expect_vram_read( 0x0AB8, 0x38 );
    ppu.step_pixel(); // 008 264 -> 008 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 265 -> 008 266
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 266 -> 008 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 267 -> 008 268
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 268 -> 008 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 269 -> 008 270
    ppu.expect_vram_read( 0x0BB0, 0x30 );
    ppu.step_pixel(); // 008 270 -> 008 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 271 -> 008 272
    ppu.expect_vram_read( 0x0BB8, 0x38 );
    ppu.step_pixel(); // 008 272 -> 008 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 273 -> 008 274
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 274 -> 008 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 275 -> 008 276
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 276 -> 008 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 277 -> 008 278
    ppu.expect_vram_read( 0x0CA7, 0x27 );
    ppu.step_pixel(); // 008 278 -> 008 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 279 -> 008 280
    ppu.expect_vram_read( 0x0CAF, 0x2F );
    ppu.step_pixel(); // 008 280 -> 008 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 281 -> 008 282
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 282 -> 008 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 283 -> 008 284
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 284 -> 008 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 285 -> 008 286
    ppu.expect_vram_read( 0x0DA7, 0x27 );
    ppu.step_pixel(); // 008 286 -> 008 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 287 -> 008 288
    ppu.expect_vram_read( 0x0DAF, 0x2F );
    ppu.step_pixel(); // 008 288 -> 008 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 289 -> 008 290
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 290 -> 008 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 291 -> 008 292
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 292 -> 008 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 293 -> 008 294
    ppu.expect_vram_read( 0x1FE6, 0x66 );
    ppu.step_pixel(); // 008 294 -> 008 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 295 -> 008 296
    ppu.expect_vram_read( 0x1FEE, 0x6E );
    ppu.step_pixel(); // 008 296 -> 008 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 297 -> 008 298
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 298 -> 008 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 299 -> 008 300
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 300 -> 008 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 301 -> 008 302
    ppu.expect_vram_read( 0x1FE6, 0x66 );
    ppu.step_pixel(); // 008 302 -> 008 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 303 -> 008 304
    ppu.expect_vram_read( 0x1FEE, 0x6E );
    ppu.step_pixel(); // 008 304 -> 008 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 305 -> 008 306
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 306 -> 008 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 307 -> 008 308
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 308 -> 008 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 309 -> 008 310
    ppu.expect_vram_read( 0x1FE6, 0x66 );
    ppu.step_pixel(); // 008 310 -> 008 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 311 -> 008 312
    ppu.expect_vram_read( 0x1FEE, 0x6E );
    ppu.step_pixel(); // 008 312 -> 008 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 313 -> 008 314
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 314 -> 008 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 315 -> 008 316
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 008 316 -> 008 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 317 -> 008 318
    ppu.expect_vram_read( 0x1FE6, 0x66 );
    ppu.step_pixel(); // 008 318 -> 008 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 008 319 -> 008 320
    ppu.expect_vram_read( 0x1FEE, 0x6E );
    ppu.step_pixel(); // 008 320 -> 008 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 009 256 -> 009 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 257 -> 009 258
    ppu.expect_vram_read( 0x2422, 0xA2 );
    ppu.step_pixel(); // 009 258 -> 009 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 259 -> 009 260
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 260 -> 009 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 261 -> 009 262
    ppu.expect_vram_read( 0x0AB1, 0x31 );
    ppu.step_pixel(); // 009 262 -> 009 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 263 -> 009 264
    ppu.expect_vram_read( 0x0AB9, 0x39 );
    ppu.step_pixel(); // 009 264 -> 009 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 265 -> 009 266
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 266 -> 009 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 267 -> 009 268
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 268 -> 009 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 269 -> 009 270
    ppu.expect_vram_read( 0x0BB1, 0x31 );
    ppu.step_pixel(); // 009 270 -> 009 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 271 -> 009 272
    ppu.expect_vram_read( 0x0BB9, 0x39 );
    ppu.step_pixel(); // 009 272 -> 009 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 273 -> 009 274
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 274 -> 009 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 275 -> 009 276
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 276 -> 009 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 277 -> 009 278
    ppu.expect_vram_read( 0x0CA6, 0x26 );
    ppu.step_pixel(); // 009 278 -> 009 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 279 -> 009 280
    ppu.expect_vram_read( 0x0CAE, 0x2E );
    ppu.step_pixel(); // 009 280 -> 009 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 281 -> 009 282
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 282 -> 009 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 283 -> 009 284
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 284 -> 009 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 285 -> 009 286
    ppu.expect_vram_read( 0x0DA6, 0x26 );
    ppu.step_pixel(); // 009 286 -> 009 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 287 -> 009 288
    ppu.expect_vram_read( 0x0DAE, 0x2E );
    ppu.step_pixel(); // 009 288 -> 009 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 289 -> 009 290
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 290 -> 009 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 291 -> 009 292
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 292 -> 009 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 293 -> 009 294
    ppu.expect_vram_read( 0x1FE5, 0x65 );
    ppu.step_pixel(); // 009 294 -> 009 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 295 -> 009 296
    ppu.expect_vram_read( 0x1FED, 0x6D );
    ppu.step_pixel(); // 009 296 -> 009 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 297 -> 009 298
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 298 -> 009 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 299 -> 009 300
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 300 -> 009 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 301 -> 009 302
    ppu.expect_vram_read( 0x1FE5, 0x65 );
    ppu.step_pixel(); // 009 302 -> 009 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 303 -> 009 304
    ppu.expect_vram_read( 0x1FED, 0x6D );
    ppu.step_pixel(); // 009 304 -> 009 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 305 -> 009 306
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 306 -> 009 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 307 -> 009 308
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 308 -> 009 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 309 -> 009 310
    ppu.expect_vram_read( 0x1FE5, 0x65 );
    ppu.step_pixel(); // 009 310 -> 009 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 311 -> 009 312
    ppu.expect_vram_read( 0x1FED, 0x6D );
    ppu.step_pixel(); // 009 312 -> 009 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 313 -> 009 314
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 314 -> 009 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 315 -> 009 316
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 009 316 -> 009 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 317 -> 009 318
    ppu.expect_vram_read( 0x1FE5, 0x65 );
    ppu.step_pixel(); // 009 318 -> 009 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 009 319 -> 009 320
    ppu.expect_vram_read( 0x1FED, 0x6D );
    ppu.step_pixel(); // 009 320 -> 009 321
    ppu.step_scanline();
    for _ in 0..257u32 {
        ppu.step_pixel();
    } // 010 256 -> 010 257
    ppu.write_secondary_sprite_ram( 0, 0xFF );
    ppu.write_secondary_sprite_ram( 1, 0xFF );
    ppu.write_secondary_sprite_ram( 2, 0xFF );
    ppu.write_secondary_sprite_ram( 3, 0xFF );
    ppu.write_secondary_sprite_ram( 4, 0xFF );
    ppu.write_secondary_sprite_ram( 5, 0xFF );
    ppu.write_secondary_sprite_ram( 6, 0xFF );
    ppu.write_secondary_sprite_ram( 7, 0xFF );
    ppu.write_secondary_sprite_ram( 8, 0xFF );
    ppu.write_secondary_sprite_ram( 9, 0xFF );
    ppu.write_secondary_sprite_ram( 10, 0xFF );
    ppu.write_secondary_sprite_ram( 11, 0xFF );
    ppu.write_secondary_sprite_ram( 12, 0xFF );
    ppu.write_secondary_sprite_ram( 13, 0xFF );
    ppu.write_secondary_sprite_ram( 14, 0xFF );
    ppu.write_secondary_sprite_ram( 15, 0xFF );
    ppu.write_secondary_sprite_ram( 16, 0xFF );
    ppu.write_secondary_sprite_ram( 17, 0xFF );
    ppu.write_secondary_sprite_ram( 18, 0xFF );
    ppu.write_secondary_sprite_ram( 19, 0xFF );
    ppu.write_secondary_sprite_ram( 20, 0xFF );
    ppu.write_secondary_sprite_ram( 21, 0xFF );
    ppu.write_secondary_sprite_ram( 22, 0xFF );
    ppu.write_secondary_sprite_ram( 23, 0xFF );
    ppu.write_secondary_sprite_ram( 24, 0xFF );
    ppu.write_secondary_sprite_ram( 25, 0xFF );
    ppu.write_secondary_sprite_ram( 26, 0xFF );
    ppu.write_secondary_sprite_ram( 27, 0xFF );
    ppu.write_secondary_sprite_ram( 28, 0xFF );
    ppu.write_secondary_sprite_ram( 29, 0xFF );
    ppu.write_secondary_sprite_ram( 30, 0xFF );
    ppu.write_secondary_sprite_ram( 31, 0xFF );
    ppu.write_secondary_sprite_ram( 0, 0x00 );
    ppu.write_secondary_sprite_ram( 1, 0xAA );
    ppu.write_secondary_sprite_ram( 2, 0x00 );
    ppu.write_secondary_sprite_ram( 3, 0x00 );
    ppu.write_secondary_sprite_ram( 4, 0x00 );
    ppu.write_secondary_sprite_ram( 5, 0xBA );
    ppu.write_secondary_sprite_ram( 6, 0x40 );
    ppu.write_secondary_sprite_ram( 7, 0x08 );
    ppu.write_secondary_sprite_ram( 8, 0x00 );
    ppu.write_secondary_sprite_ram( 9, 0xCA );
    ppu.write_secondary_sprite_ram( 10, 0x80 );
    ppu.write_secondary_sprite_ram( 11, 0x10 );
    ppu.write_secondary_sprite_ram( 12, 0x00 );
    ppu.write_secondary_sprite_ram( 13, 0xDA );
    ppu.write_secondary_sprite_ram( 14, 0xC0 );
    ppu.write_secondary_sprite_ram( 15, 0x18 );
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 257 -> 010 258
    ppu.expect_vram_read( 0x2422, 0xA2 );
    ppu.step_pixel(); // 010 258 -> 010 259
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 259 -> 010 260
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 260 -> 010 261
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 261 -> 010 262
    ppu.expect_vram_read( 0x0AB2, 0x32 );
    ppu.step_pixel(); // 010 262 -> 010 263
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 263 -> 010 264
    ppu.expect_vram_read( 0x0ABA, 0x3A );
    ppu.step_pixel(); // 010 264 -> 010 265
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 265 -> 010 266
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 266 -> 010 267
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 267 -> 010 268
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 268 -> 010 269
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 269 -> 010 270
    ppu.expect_vram_read( 0x0BB2, 0x32 );
    ppu.step_pixel(); // 010 270 -> 010 271
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 271 -> 010 272
    ppu.expect_vram_read( 0x0BBA, 0x3A );
    ppu.step_pixel(); // 010 272 -> 010 273
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 273 -> 010 274
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 274 -> 010 275
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 275 -> 010 276
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 276 -> 010 277
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 277 -> 010 278
    ppu.expect_vram_read( 0x0CA5, 0x25 );
    ppu.step_pixel(); // 010 278 -> 010 279
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 279 -> 010 280
    ppu.expect_vram_read( 0x0CAD, 0x2D );
    ppu.step_pixel(); // 010 280 -> 010 281
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 281 -> 010 282
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 282 -> 010 283
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 283 -> 010 284
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 284 -> 010 285
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 285 -> 010 286
    ppu.expect_vram_read( 0x0DA5, 0x25 );
    ppu.step_pixel(); // 010 286 -> 010 287
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 287 -> 010 288
    ppu.expect_vram_read( 0x0DAD, 0x2D );
    ppu.step_pixel(); // 010 288 -> 010 289
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 289 -> 010 290
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 290 -> 010 291
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 291 -> 010 292
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 292 -> 010 293
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 293 -> 010 294
    ppu.expect_vram_read( 0x1FE4, 0x64 );
    ppu.step_pixel(); // 010 294 -> 010 295
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 295 -> 010 296
    ppu.expect_vram_read( 0x1FEC, 0x6C );
    ppu.step_pixel(); // 010 296 -> 010 297
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 297 -> 010 298
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 298 -> 010 299
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 299 -> 010 300
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 300 -> 010 301
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 301 -> 010 302
    ppu.expect_vram_read( 0x1FE4, 0x64 );
    ppu.step_pixel(); // 010 302 -> 010 303
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 303 -> 010 304
    ppu.expect_vram_read( 0x1FEC, 0x6C );
    ppu.step_pixel(); // 010 304 -> 010 305
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 305 -> 010 306
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 306 -> 010 307
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 307 -> 010 308
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 308 -> 010 309
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 309 -> 010 310
    ppu.expect_vram_read( 0x1FE4, 0x64 );
    ppu.step_pixel(); // 010 310 -> 010 311
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 311 -> 010 312
    ppu.expect_vram_read( 0x1FEC, 0x6C );
    ppu.step_pixel(); // 010 312 -> 010 313
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 313 -> 010 314
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 314 -> 010 315
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 315 -> 010 316
    ppu.expect_vram_read( 0x2020, 0xA0 );
    ppu.step_pixel(); // 010 316 -> 010 317
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 317 -> 010 318
    ppu.expect_vram_read( 0x1FE4, 0x64 );
    ppu.step_pixel(); // 010 318 -> 010 319
    ppu.expect_no_vram_read();
    ppu.step_pixel(); // 010 319 -> 010 320
    ppu.expect_vram_read( 0x1FEC, 0x6C );
    ppu.step_pixel(); // 010 320 -> 010 321
    ppu.step_scanline();
    assert_eq!( ppu.scanline(), 11 );
    assert_eq!( ppu.dot(), 0 );
}
